// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg7_yYlNi_6qa09ksi-Zp9mtFzc8OGT5s',
    appId: '1:751232317405:web:a4587c8b8d6ee886022834',
    messagingSenderId: '751232317405',
    projectId: 'barcode-for-expiration-date',
    authDomain: 'barcode-for-expiration-date.firebaseapp.com',
    storageBucket: 'barcode-for-expiration-date.appspot.com',
    measurementId: 'G-GEH7G48P5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOEFu6F_riGKvhn1MHbKDDIKQeI4hVZF8',
    appId: '1:751232317405:android:ffbd507ee1ddf130022834',
    messagingSenderId: '751232317405',
    projectId: 'barcode-for-expiration-date',
    storageBucket: 'barcode-for-expiration-date.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4TNCkq9BRUCMsyCYEnRCs98GDeZnJor0',
    appId: '1:751232317405:ios:71b6ba185f2adaa3022834',
    messagingSenderId: '751232317405',
    projectId: 'barcode-for-expiration-date',
    storageBucket: 'barcode-for-expiration-date.appspot.com',
    iosBundleId: 'com.vitamin.barcodeScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4TNCkq9BRUCMsyCYEnRCs98GDeZnJor0',
    appId: '1:751232317405:ios:f10196eace201a5e022834',
    messagingSenderId: '751232317405',
    projectId: 'barcode-for-expiration-date',
    storageBucket: 'barcode-for-expiration-date.appspot.com',
    iosBundleId: 'com.example.barcodeScanner.RunnerTests',
  );
}
